name: hydromt-sfincs

channels:
  - conda-forge

dependencies:
  - affine
  - click
  - black
  - bottleneck
  - cartopy # to run examples
  - dask
  - descartes # to run examples
  - entrypoints
  - ffmpeg  # to run examples (animation)
  - flit>=3.2
  # - git  # to install git repositories with pip
  - gdal>=3.1
  - geopandas
  - hydromt>=0.4.5
  - jupyterlab # to run examples
  - netcdf4
  - matplotlib # to run examples
  - numba
  - numpy
  - openpyxl
  - pandas
  - pip
  - pyflwdir>=0.5.5
  - pygeos>=0.8
  - python>=3.7
  - rasterio
  - requests
  - scipy
  - xarray
  - zarr
  # - pip:
  #   - git+https://github.com/Deltares/hydromt.git

